#first neural network practice 
#creating one small perceptron to understand its working
#using numpy for creating arrays and functions and we will do back propagation too to understand 
#how adjustment of the weights work
#neural network is just a mathematicala replica of our brain and a single layered neural network that is 
#perceptron is just equivalent to a single neuron

In [57]:
#Importing numpy library
import numpy as np

In [58]:
#lets assign our input array or training inputs
training_input = np.array([[0,0,1],
                          [1,1,1],
                          [1,0,1],
                          [0,1,1]])

In [59]:
#our actual outputs 
#here T is for transpose the array
training_output = np.array([[0,1,1,0]]).T

In [60]:
#lets create random genrated weights but keep it constant for all our iterations
#(3,1) is the dimension of the weight array
#we will use this weights afterwords so we will keep the genrated weights constant
np.random.seed(1)
#3 inputs hence 3 *1 matrix and values between -1 to 1
synaptic_weights = 2 * np.random.random((3,1)) - 1
print(synaptic_weights)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [61]:
#defining the sigmoid function for activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
#for now we will not adjust our weights and errors
#to see how much error we get

In [62]:
'''#now lets calculate the output
#which is sum of dot products of input values and their weights times the activation function
for i in range(1):
    output = sigmoid(np.dot(training_input,synaptic_weights))
print(output)'''

'#now lets calculate the output\n#which is sum of dot products of input values and their weights times the activation function\nfor i in range(1):\n    output = sigmoid(np.dot(training_input,synaptic_weights))\nprint(output)'

In [63]:
#as we can see the difference between ouput and the training output is significant
#we can reduce this by adjusting the weights
#to do this we need the derivative of sigmoid
def derivative_sigmoid(x):
    return x * (1 - x)

In [67]:
#we have to calculate the error and adjustments 
#we have to update our weights accordingly
#which is the dot product of a Transpose of the input matrix and the adjustments
for i in range(500000):
        output = sigmoid(np.dot(training_input,synaptic_weights))
        error = training_output - output
        adjustment = error * derivative_sigmoid(output)
        synaptic_weights += np.dot(training_input.T,adjustment)
print(output)

[[0.00125963]
 [0.9989717 ]
 [0.99916084]
 [0.00102799]]


In [68]:
print(synaptic_weights)

[[13.75794128]
 [-0.20344092]
 [-6.67567642]]
